spring:
  datasource:
    url: jdbc:mysql://172.29.234.167:3306/dataease?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Password123@mysql
  messages:
    basename: i18n/lic,i18n/core,i18n/permissions,i18n/xpack
  flyway:
    enabled: false

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml


